SAVED QA
{
    "question": "3333333333333333333333333333333",
    "savedQuestionID": 2,
    "option1": "333333333333333",
    "option2": "44",
    "option3": "33333333333333",
    "option4": "43333333333333333333333333",
    "type": 5,
    "tamplateId": 6,
    "savedQuestions": true
    }

NEW Q TYPE 3
{
    "question": "Are there more people in Fiji than in Cape Verde?",
    "XXX": "Fiji",
    "YYY": "Cape Verde",
    "type": 3,
    "tamplateId": 14,
    "savedQuestions": false,
    "column": "population"
    }

    
    
NEW Q TYPE 2
{
    "question": "What is the capital of Western Sahara?",
    "option1": "El-Aaiún",
    "option2": "Port Moresby",
    "option3": "Charlotte Amalie",
    "option4": "Banjul",
    "XXX": "Western Sahara",
    "type": 2,
    "tamplateId": 11,
    "savedQuestions": false,
    "column": "Capital"
    }

NEW Q TYPE 1
{
    "question": "Which country is least populous?",
    "option1": "Portugal",
    "option2": "Bolivia",
    "option3": "India",
    "option4": "Benin",
    "type": 1,
    "tamplateId": 2,
    "savedQuestions": false,
    "column": "Population"
    }

ALL ANSWERS
{
    "answer": "true"
}