POST  https://hallowed-key-312708.ew.r.appspot.com/users/register
Content-Type: application/json

{ 
    "email": "zx@g.com",
    "username": "zx",
    "password" : "zx" 
}
###
POST  https://hallowed-key-312708.ew.r.appspot.com/users/login
Content-Type: application/json

{ 
    
    "username": "amit",
    "password" : "123" 
}
###
POST  https://hallowed-key-312708.ew.r.appspot.com/users/newtoken
Content-Type: application/json
refreshToken: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXQiLCJpYXQiOjE2MTk4OTYyNzIsImV4cCI6MTYxOTkxMDY3Mn0._IpWovHvKZZchLFCApPZBL42vsCbr-iz7yTZeuwaQqk

{ 
    
    
}
###
POST https://hallowed-key-312708.ew.r.appspot.com/users/logout
Content-Type: application/json
refreshtoken: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXQiLCJpYXQiOjE2MTk3OTEzMjYsImV4cCI6MTYxOTgwNTcyNn0.1irGnkyWhG0s6WTaPvTyTd4sc1wMXRmJRp0geo6zHYk
accesstoken: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXQiLCJpYXQiOjE2MTk3OTQxOTksImV4cCI6MTYxOTc5NDkxOX0.WpOUkJBhe_8tvn3xqfuaKVlYKNm_iKfauv644T1xe_8 

{

}

###
GET  https://hallowed-key-312708.ew.r.appspot.com/newQuestion
Content-Type: application/json
refreshtoken: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXQiLCJpYXQiOjE2MTk3OTEzMjYsImV4cCI6MTYxOTgwNTcyNn0.1irGnkyWhG0s6WTaPvTyTd4sc1wMXRmJRp0geo6zHYk
accesstoken: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXQiLCJpYXQiOjE2MTk3OTQxOTksImV4cCI6MTYxOTc5NDkxOX0.WpOUkJBhe_8tvn3xqfuaKVlYKNm_iKfauv644T1xe_8 

{

}

###
POST https://hallowed-key-312708.ew.r.appspot.com/players
Content-Type: application/json
refreshtoken: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXQiLCJpYXQiOjE2MTk4OTcxOTgsImV4cCI6MTYxOTg5NzIwOH0.GkJyxbWoFWB4XXYF_2o45R_T1GzHBt3mH_dQILjkaP4
accesstoken: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXQiLCJpYXQiOjE2MTk4OTc2MjUsImV4cCI6MTYxOTg5NzYzNX0.7u7sbeC0IWXIcSyygYkl4TiNfsYk5VzhnlarVanMg_M

{
    "name" : "situ" ,
    "score" : 9
}